[GLOBAL]
pants_version = "2.12.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.black",
  "pants.backend.python.typecheck.mypy"
]

[anonymous-telemetry]
enabled = false

[python]
enable_resolves = true

# Enable using the PEX lockfile format, which provides support for custom indexes, and
# improves performance for large repositories.
lockfile_generator = "pex"
